# Generated by Django 4.2.7 on 2023-11-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_remove_user_id_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adminFlag',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='clientFlag',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
