# Generated by Django 4.2.7 on 2023-11-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0003_user_adminflag_user_age_user_clientflag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adminFlag',
            new_name='admin_flag',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='clientFlag',
            new_name='client_flag',
        ),
    ]
