# Generated by Django 4.2.7 on 2023-11-16 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0004_rename_adminflag_user_admin_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
