# Generated by Django 4.2.7 on 2023-11-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0005_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_flag',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='client_flag',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
