# Generated by Django 4.2.7 on 2023-11-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0006_alter_user_admin_flag_alter_user_client_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='client_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('age__gt', 0), ('age__lte', 120)), name='check_age'),
        ),
    ]
