# Generated by Django 4.2.7 on 2023-11-21 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0007_alter_user_admin_flag_alter_user_client_flag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('date_released', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=15, null=True)),
                ('bio', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('date_released', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Song_Rating',
            fields=[
                ('rating_id', models.IntegerField(primary_key=True, serialize=False)),
                ('originality_score', models.IntegerField()),
                ('lyric_score', models.IntegerField()),
                ('vibe_score', models.IntegerField()),
                ('instrumental_score', models.IntegerField()),
                ('date_given', models.DateField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='check_age',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('age__gt', 0), ('age__lte', 120)), name='check_user_age'),
        ),
        migrations.AddField(
            model_name='song_rating',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.song'),
        ),
        migrations.AddField(
            model_name='song_rating',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.user'),
        ),
        migrations.AddField(
            model_name='song',
            name='album_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FirstApp.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.artist'),
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.CheckConstraint(check=models.Q(('age__gt', 0), ('age__lte', 120)), name='check_artist_age'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.artist'),
        ),
        migrations.AddConstraint(
            model_name='song_rating',
            constraint=models.CheckConstraint(check=models.Q(('originality_score__gte', 0), ('originality_score__lte', 10)), name='check_song_rating_originality_score'),
        ),
        migrations.AddConstraint(
            model_name='song_rating',
            constraint=models.CheckConstraint(check=models.Q(('lyric_score__gte', 0), ('lyric_score__lte', 10)), name='check_song_rating_lyric_score'),
        ),
        migrations.AddConstraint(
            model_name='song_rating',
            constraint=models.CheckConstraint(check=models.Q(('vibe_score__gte', 0), ('vibe_score__lte', 10)), name='check_song_rating_vibe_score'),
        ),
        migrations.AddConstraint(
            model_name='song_rating',
            constraint=models.CheckConstraint(check=models.Q(('instrumental_score__gte', 0), ('instrumental_score__lte', 10)), name='check_song_rating_instrumental_score'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('song_id', 'artist_id'), name='song_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('album_id', 'artist_id'), name='album_primary_key'),
        ),
    ]
