# Generated by Django 4.2.7 on 2023-11-22 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0009_alter_artist_bio_alter_artist_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FirstApp.album'),
        ),
    ]
