# Generated by Django 4.2.7 on 2023-11-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0010_alter_song_album_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song_rating',
            name='date_given',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
