# Generated by Django 4.2.7 on 2023-11-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0011_alter_song_rating_date_given_alter_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song_rating',
            name='song_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album_id',
        ),
        migrations.RemoveField(
            model_name='album',
            name='id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AlterField(
            model_name='album',
            name='album_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
