# Generated by Django 4.2.7 on 2023-11-22 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0012_remove_album_id_remove_song_album_id_remove_song_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FirstApp.album'),
        ),
        migrations.AddField(
            model_name='song_rating',
            name='song_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='FirstApp.song'),
            preserve_default=False,
        ),
    ]
