# Generated by Django 4.2.7 on 2023-11-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0013_song_album_id_song_rating_song_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('producer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(blank=True, max_length=15)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='producer',
            constraint=models.CheckConstraint(check=models.Q(('age__gt', 0), ('age__lte', 120)), name='check_producer_age'),
        ),
    ]
