# Generated by Django 4.2.7 on 2023-11-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0014_producer_producer_check_producer_age'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='song_rating',
            constraint=models.UniqueConstraint(fields=('rating_id', 'username'), name='song_rating_primary_key'),
        ),
    ]
