# Generated by Django 4.2.7 on 2023-11-22 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0015_song_rating_song_rating_primary_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album_Rating',
            fields=[
                ('rating_id', models.IntegerField(primary_key=True, serialize=False)),
                ('originality_score', models.IntegerField()),
                ('lyric_score', models.IntegerField()),
                ('vibe_score', models.IntegerField()),
                ('instrumental_score', models.IntegerField()),
                ('album_flow_score', models.IntegerField()),
                ('date_given', models.DateField(auto_now_add=True)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.album')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='album_rating',
            constraint=models.CheckConstraint(check=models.Q(('originality_score__gte', 0), ('originality_score__lte', 10)), name='check_album_rating_originality_score'),
        ),
        migrations.AddConstraint(
            model_name='album_rating',
            constraint=models.CheckConstraint(check=models.Q(('lyric_score__gte', 0), ('lyric_score__lte', 10)), name='check_album_rating_lyric_score'),
        ),
        migrations.AddConstraint(
            model_name='album_rating',
            constraint=models.CheckConstraint(check=models.Q(('vibe_score__gte', 0), ('vibe_score__lte', 10)), name='check_album_rating_vibe_score'),
        ),
        migrations.AddConstraint(
            model_name='album_rating',
            constraint=models.CheckConstraint(check=models.Q(('instrumental_score__gte', 0), ('instrumental_score__lte', 10)), name='check_album_rating_instrumental_score'),
        ),
        migrations.AddConstraint(
            model_name='album_rating',
            constraint=models.CheckConstraint(check=models.Q(('album_flow_score__gte', 0), ('album_flow_score__lte', 10)), name='check_album_rating_album_flow_score'),
        ),
        migrations.AddConstraint(
            model_name='album_rating',
            constraint=models.UniqueConstraint(fields=('rating_id', 'username'), name='album_rating_primary_key'),
        ),
    ]
