# Generated by Django 4.2.7 on 2023-11-22 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0016_album_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song_Review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('rating_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.song_rating')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.song')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Album_Review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.album')),
                ('rating_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.album_rating')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='song_review',
            constraint=models.UniqueConstraint(fields=('review_id', 'username'), name='song_review_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='album_review',
            constraint=models.UniqueConstraint(fields=('review_id', 'username'), name='album_review_primary_key'),
        ),
    ]
