# Generated by Django 4.2.7 on 2023-11-22 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0018_alter_album_album_id_alter_album_rating_rating_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song_Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.song')),
            ],
        ),
        migrations.CreateModel(
            name='Producer_Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('producer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.producer')),
            ],
        ),
        migrations.CreateModel(
            name='Artist_Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Album_Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.album')),
            ],
        ),
        migrations.AddConstraint(
            model_name='song_genre',
            constraint=models.UniqueConstraint(fields=('song_id', 'genre'), name='song_genre_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='producer_genre',
            constraint=models.UniqueConstraint(fields=('producer_id', 'genre'), name='producer_genre_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='artist_genre',
            constraint=models.UniqueConstraint(fields=('artist_id', 'genre'), name='artist_genre_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='album_genre',
            constraint=models.UniqueConstraint(fields=('album_id', 'genre'), name='album_genre_primary_key'),
        ),
    ]
