# Generated by Django 4.2.7 on 2023-11-27 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0021_alter_album_genre_genre_alter_artist_genre_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song_Review_Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('body', models.TextField()),
                ('date_posted', models.DateField()),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.song_review')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Album_Review_Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('body', models.TextField()),
                ('date_posted', models.DateField()),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.album_review')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='song_review_comment',
            constraint=models.UniqueConstraint(fields=('comment_id', 'review_id'), name='song_review_comment_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='album_review_comment',
            constraint=models.UniqueConstraint(fields=('comment_id', 'review_id'), name='album_review_comment_primary_key'),
        ),
    ]
