# Generated by Django 4.2.7 on 2023-11-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0022_song_review_comment_album_review_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_review_comment',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='song_review_comment',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
