# Generated by Django 4.2.7 on 2023-11-27 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0023_alter_album_review_comment_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_review_comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_review_comments_posted', to='FirstApp.user'),
        ),
        migrations.AlterField(
            model_name='song_review_comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_review_comments_posted', to='FirstApp.user'),
        ),
        migrations.CreateModel(
            name='Upvotes_Downvotes_Song_Review_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.BooleanField()),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.song_review_comment')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Upvotes_Downvotes_Album_Review_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.BooleanField()),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.album_review_comment')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='album_review_comment',
            name='voted_users',
            field=models.ManyToManyField(related_name='album_review_comments_voted', through='FirstApp.Upvotes_Downvotes_Album_Review_Comment', to='FirstApp.user'),
        ),
        migrations.AddField(
            model_name='song_review_comment',
            name='voted_users',
            field=models.ManyToManyField(related_name='song_review_comments_voted', through='FirstApp.Upvotes_Downvotes_Song_Review_Comment', to='FirstApp.user'),
        ),
        migrations.AddConstraint(
            model_name='upvotes_downvotes_song_review_comment',
            constraint=models.UniqueConstraint(fields=('username', 'comment_id'), name='upvotes_downvotes_song_review_comment_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='upvotes_downvotes_album_review_comment',
            constraint=models.UniqueConstraint(fields=('username', 'comment_id'), name='upvotes_downvotes_album_review_comment_primary_key'),
        ),
    ]
