# Generated by Django 4.2.7 on 2023-11-27 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0024_alter_album_review_comment_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_review',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_reviews_posted', to='FirstApp.user'),
        ),
        migrations.AlterField(
            model_name='song_review',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_reviews_posted', to='FirstApp.user'),
        ),
        migrations.CreateModel(
            name='Upvotes_Downvotes_Song_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.BooleanField()),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.song_review')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Upvotes_Downvotes_Album_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.BooleanField()),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.album_review')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='album_review',
            name='voted_users',
            field=models.ManyToManyField(related_name='album_reviews_voted', through='FirstApp.Upvotes_Downvotes_Album_Review', to='FirstApp.user'),
        ),
        migrations.AddField(
            model_name='song_review',
            name='voted_users',
            field=models.ManyToManyField(related_name='song_reviews_voted', through='FirstApp.Upvotes_Downvotes_Song_Review', to='FirstApp.user'),
        ),
        migrations.AddConstraint(
            model_name='upvotes_downvotes_song_review',
            constraint=models.UniqueConstraint(fields=('username', 'review_id'), name='upvotes_downvotes_song_review_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='upvotes_downvotes_album_review',
            constraint=models.UniqueConstraint(fields=('username', 'review_id'), name='upvotes_downvotes_album_review_primary_key'),
        ),
    ]
