# Generated by Django 4.2.7 on 2023-11-27 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0025_alter_album_review_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produces_Their_Single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.artist')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.song')),
            ],
        ),
        migrations.CreateModel(
            name='Produces_Their_Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.album')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Produces_Single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.producer')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.song')),
            ],
        ),
        migrations.CreateModel(
            name='Produces_Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.album')),
                ('producer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.producer')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='albums_produced',
            field=models.ManyToManyField(through='FirstApp.Produces_Their_Album', to='FirstApp.album'),
        ),
        migrations.AddField(
            model_name='artist',
            name='singles_produced',
            field=models.ManyToManyField(through='FirstApp.Produces_Their_Single', to='FirstApp.song'),
        ),
        migrations.AddField(
            model_name='producer',
            name='albums_produced',
            field=models.ManyToManyField(through='FirstApp.Produces_Album', to='FirstApp.album'),
        ),
        migrations.AddField(
            model_name='producer',
            name='singles_produced',
            field=models.ManyToManyField(through='FirstApp.Produces_Single', to='FirstApp.song'),
        ),
        migrations.AddConstraint(
            model_name='produces_their_single',
            constraint=models.UniqueConstraint(fields=('artist_id', 'song_id'), name='produces_their_single_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='produces_their_album',
            constraint=models.UniqueConstraint(fields=('artist_id', 'album_id'), name='produces_their_album_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='produces_single',
            constraint=models.UniqueConstraint(fields=('producer_id', 'song_id'), name='produces_single_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='produces_album',
            constraint=models.UniqueConstraint(fields=('producer_id', 'album_id'), name='produces_album_primary_key'),
        ),
    ]
