# Generated by Django 4.2.7 on 2023-11-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0026_produces_their_single_produces_their_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(),
        ),
    ]
