# Generated by Django 4.2.7 on 2023-11-28 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0027_alter_artist_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='FirstApp.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='FirstApp.artist'),
        ),
    ]
