# Generated by Django 4.2.7 on 2023-11-28 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0028_alter_song_album_id_alter_song_artist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='FirstApp.artist'),
        ),
        migrations.AlterField(
            model_name='album_genre',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='FirstApp.album'),
        ),
        migrations.AlterField(
            model_name='album_rating',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='FirstApp.album'),
        ),
        migrations.AlterField(
            model_name='album_rating',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_ratings', to='FirstApp.user'),
        ),
        migrations.AlterField(
            model_name='album_review',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='FirstApp.album'),
        ),
        migrations.AlterField(
            model_name='album_review',
            name='rating_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='FirstApp.album_rating'),
        ),
        migrations.AlterField(
            model_name='album_review_comment',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='FirstApp.album_review'),
        ),
        migrations.AlterField(
            model_name='artist_genre',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='FirstApp.artist'),
        ),
        migrations.AlterField(
            model_name='producer_genre',
            name='producer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='FirstApp.producer'),
        ),
        migrations.AlterField(
            model_name='song_genre',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='FirstApp.song'),
        ),
        migrations.AlterField(
            model_name='song_rating',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='FirstApp.song'),
        ),
        migrations.AlterField(
            model_name='song_rating',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_ratings', to='FirstApp.user'),
        ),
        migrations.AlterField(
            model_name='song_review',
            name='rating_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='FirstApp.song_rating'),
        ),
        migrations.AlterField(
            model_name='song_review',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='FirstApp.song'),
        ),
        migrations.AlterField(
            model_name='song_review_comment',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='FirstApp.song_review'),
        ),
    ]
