# Generated by Django 4.2.7 on 2023-11-30 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FirstApp', '0029_alter_album_artist_id_alter_album_genre_album_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_rating',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='album_review',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_reviews_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='album_review',
            name='voted_users',
            field=models.ManyToManyField(related_name='album_reviews_voted', through='FirstApp.Upvotes_Downvotes_Album_Review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='album_review_comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_review_comments_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='album_review_comment',
            name='voted_users',
            field=models.ManyToManyField(related_name='album_review_comments_voted', through='FirstApp.Upvotes_Downvotes_Album_Review_Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song_rating',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song_review',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_reviews_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song_review',
            name='voted_users',
            field=models.ManyToManyField(related_name='song_reviews_voted', through='FirstApp.Upvotes_Downvotes_Song_Review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song_review_comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_review_comments_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song_review_comment',
            name='voted_users',
            field=models.ManyToManyField(related_name='song_review_comments_voted', through='FirstApp.Upvotes_Downvotes_Song_Review_Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upvotes_downvotes_album_review',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upvotes_downvotes_album_review_comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upvotes_downvotes_song_review',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upvotes_downvotes_song_review_comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(check=models.Q(('age__gt', 0), ('age__lte', 120)), name='check_user_age'),
        ),
    ]
