# Generated by Django 4.2.7 on 2023-12-01 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0029_alter_album_artist_id_alter_album_genre_album_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='artist',
            name='check_artist_age',
        ),
        migrations.RemoveConstraint(
            model_name='producer',
            name='check_producer_age',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='age',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='gender',
        ),
    ]
