# Generated by Django 4.2.7 on 2023-12-01 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0030_profile_alter_album_rating_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
