# Generated by Django 4.2.7 on 2023-12-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0032_remove_artist_check_artist_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='albums_produced',
            field=models.ManyToManyField(related_name='artist_producers', through='FirstApp.Produces_Their_Album', to='FirstApp.album'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='singles_produced',
            field=models.ManyToManyField(related_name='artist_producers', through='FirstApp.Produces_Their_Single', to='FirstApp.song'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='albums_produced',
            field=models.ManyToManyField(related_name='producers', through='FirstApp.Produces_Album', to='FirstApp.album'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='singles_produced',
            field=models.ManyToManyField(related_name='producers', through='FirstApp.Produces_Single', to='FirstApp.song'),
        ),
    ]
