# Generated by Django 4.2.7 on 2023-12-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0033_alter_artist_albums_produced_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='song_rating',
            name='song_rating_primary_key',
        ),
        migrations.AddConstraint(
            model_name='song_rating',
            constraint=models.UniqueConstraint(fields=('song_id', 'username'), name='song_rating_primary_key'),
        ),
    ]
