# Generated by Django 4.2.7 on 2023-12-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0034_remove_song_rating_song_rating_primary_key_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='album_rating',
            name='album_rating_primary_key',
        ),
        migrations.AddConstraint(
            model_name='album_rating',
            constraint=models.UniqueConstraint(fields=('album_id', 'username'), name='album_rating_primary_key'),
        ),
    ]
