# Generated by Django 4.2.7 on 2023-12-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0035_remove_album_rating_album_rating_primary_key_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='album_review',
            name='album_review_primary_key',
        ),
        migrations.RemoveConstraint(
            model_name='song_review',
            name='song_review_primary_key',
        ),
        migrations.AddConstraint(
            model_name='album_review',
            constraint=models.UniqueConstraint(fields=('album_id', 'username'), name='album_review_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='song_review',
            constraint=models.UniqueConstraint(fields=('song_id', 'username'), name='song_review_primary_key'),
        ),
    ]
